cache_dir: ./data/


comm:
  # 触发的命令 ys#游戏UID
  player_uid: ys#

#必须设置才能使用 可以登录米游社 获取cookie 主要内容为 account_id=******; cookie_token=*********;
#py -m pip install sqlitedict -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
#py -m pip install filetype -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
#py -m pip install html2text -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
cookie: account_id=264475285; cookie_token=wqvdlEdFWtlmpSoznLxpK2xB7ahHVON0Y92CwNIM;